//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ventaVehiculosModels.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public int IdCar { get; set; }
        public string brand { get; set; }
        public int people_capacity { get; set; }
        public string transmission_type { get; set; }
    }
}
