//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ventaVehiculosModels.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginUser
    {
        public long idUser { get; set; }
        public string UserStr { get; set; }
        public string pass { get; set; }
        public bool IsActive { get; set; }
    }
}
